import { TRANSPORT_STATES } from '../constants/states';

let state = TRANSPORT_STATES.IDLE;
let listeners = [];

const transitions = {
  [TRANSPORT_STATES.IDLE]: [TRANSPORT_STATES.SCANNING, TRANSPORT_STATES.AUTO_CONNECTING],
  [TRANSPORT_STATES.SCANNING]: [TRANSPORT_STATES.DISCOVERED, TRANSPORT_STATES.IDLE],
  [TRANSPORT_STATES.DISCOVERED]: [TRANSPORT_STATES.PAIRING, TRANSPORT_STATES.SCANNING],
  [TRANSPORT_STATES.PAIRING]: [TRANSPORT_STATES.PAIRED, TRANSPORT_STATES.SCANNING, TRANSPORT_STATES.FAILED],
  [TRANSPORT_STATES.PAIRED]: [TRANSPORT_STATES.CONNECTED, TRANSPORT_STATES.AUTO_CONNECTING, TRANSPORT_STATES.FAILED],
  [TRANSPORT_STATES.AUTO_CONNECTING]: [TRANSPORT_STATES.CONNECTED, TRANSPORT_STATES.SCANNING, TRANSPORT_STATES.FAILED],
  [TRANSPORT_STATES.CONNECTED]: [TRANSPORT_STATES.CALLING, TRANSPORT_STATES.INCOMING, TRANSPORT_STATES.IN_CALL, TRANSPORT_STATES.RECONNECTING, TRANSPORT_STATES.DISCONNECTED],
  [TRANSPORT_STATES.CALLING]: [TRANSPORT_STATES.IN_CALL, TRANSPORT_STATES.CONNECTED, TRANSPORT_STATES.RECONNECTING, TRANSPORT_STATES.FAILED],
  [TRANSPORT_STATES.INCOMING]: [TRANSPORT_STATES.IN_CALL, TRANSPORT_STATES.CONNECTED, TRANSPORT_STATES.RECONNECTING, TRANSPORT_STATES.FAILED],
  [TRANSPORT_STATES.IN_CALL]: [TRANSPORT_STATES.CONNECTED, TRANSPORT_STATES.RECONNECTING, TRANSPORT_STATES.FAILED],
  [TRANSPORT_STATES.RECONNECTING]: [TRANSPORT_STATES.CONNECTED, TRANSPORT_STATES.FAILED, TRANSPORT_STATES.IDLE],
  [TRANSPORT_STATES.DISCONNECTED]: [TRANSPORT_STATES.RECONNECTING, TRANSPORT_STATES.SCANNING, TRANSPORT_STATES.IDLE, TRANSPORT_STATES.AUTO_CONNECTING],
  [TRANSPORT_STATES.FAILED]: [TRANSPORT_STATES.IDLE, TRANSPORT_STATES.SCANNING, TRANSPORT_STATES.AUTO_CONNECTING],
};

export const TransportStateManager = {
  getState: () => state,

  canTransition: (from, to) => (transitions[from] || []).includes(to),

  setState: (next) => {
    if (next === state) {
      return;
    }
    if (!TransportStateManager.canTransition(state, next)) {
      return;
    }
    state = next;
    listeners.forEach((fn) => fn(state));
  },

  subscribe: (fn) => {
    listeners.push(fn);
    fn(state);
    return () => {
      listeners = listeners.filter((x) => x !== fn);
    };
  },
};
